#! /usr/bin/env php

<?php

require 'vendor/autoload.php';

$app = new \Symfony\Component\Console\Application('PHP Euler', '0.1');
$app->config = include 'config/config.php';

$app->add(new \Euler\SetupCommand);
$app->add(new \Euler\CreateCommand(new \Goutte\Client));
$app->add(new \Euler\NextCommand);
$app->add(new \Euler\ImportCommand);
$app->add(new \Euler\ExportCommand);
$app->run();
